/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "surface-gray": "#F8FAFC",
        "primary-fixed-dim": "#4edea3",
        "on-tertiary-container": "#711419",
        "inverse-primary": "#4edea3",
        "secondary-container": "#2170e4",
        "error-container": "#ffdad6",
        "outline": "#6c7a71",
        "secondary-fixed": "#d8e2ff",
        "surface-dim": "#cbdbf5",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#ffb3af",
        "on-tertiary": "#ffffff",
        "surface-container": "#e5eeff",
        "surface-container-highest": "#d3e4fe",
        "surface-bright": "#f8f9ff",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "on-surface": "#0b1c30",
        "outline-variant": "#bbcabf",
        "surface-container-lowest": "#ffffff",
        "background": "#f8f9ff",
        "primary-fixed": "#6ffbbe",
        "on-secondary-fixed-variant": "#004395",
        "status-amber": "#F59E0B",
        "primary": "#006c49",
        "on-surface-variant": "#3c4a42",
        "surface-container-low": "#eff4ff",
        "tertiary-fixed": "#ffdad7",
        "border-light": "#E2E8F0",
        "tertiary": "#a43a3a",
        "surface-tint": "#006c49",
        "on-secondary-fixed": "#001a42",
        "secondary": "#0058be",
        "surface-variant": "#d3e4fe",
        "on-secondary-container": "#fefcff",
        "on-primary-fixed": "#002113",
        "inverse-on-surface": "#eaf1ff",
        "on-primary-container": "#00422b",
        "on-tertiary-fixed": "#410005",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#842225",
        "status-red": "#EF4444",
        "on-primary-fixed-variant": "#005236",
        "secondary-fixed-dim": "#adc6ff",
        "primary-container": "#10b981",
        "inverse-surface": "#213145",
        "tertiary-container": "#fc7c78",
        "surface": "#f8f9ff",
        "on-background": "#0b1c30",
        "on-error-container": "#93000a"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "container-max": "1440px",
        "sidebar-width": "260px",
        "base": "4px",
        "margin-mobile": "16px",
        "gutter": "24px"
      },
      "fontFamily": {
        "display-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "display-lg": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "500" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "18px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
